### ISSUE TITLE
Test suite failing

### ISSUE THREAD

**Issue by Millak** [jaytaylor/html2text#53]
After the merge of #49 I found the test suite is failing. Going back to the previous commit makes it pass again.

starting phase `check'
--- FAIL: TestLinks (0.00s)
    html2text_test.go:469: error: input did not match specified expression
        Input:
        >>>>
        <a href="http://www.google.com" >http://www.google.com</a>
        <<<<

        Output:
        >>>>
        http://www.google.com ( http://www.google.com )
        <<<<

        Expected:
        >>>>
        http://www.google.com
        <<<<
--- FAIL: TestOmitLinks (0.00s)
    html2text_test.go:517: error: input did not match specified expression
        Input:
        >>>>
        <a href="http://example.com/"></a>
        <<<<

        Output:
        >>>>
        ( http://example.com/ )
        <<<<

        Expected:
        >>>>

        <<<<
    html2text_test.go:517: error: input did not match specified expression
        Input:
        >>>>
        <a href="http://example.com/">Link</a>
        <<<<

        Output:
        >>>>
        Link ( http://example.com/ )
        <<<<

        Expected:
        >>>>
        Link
        <<<<
    html2text_test.go:517: error: input did not match specified expression
        Input:
        >>>>
        <a href="http://example.com/"><span class="a">Link</span></a>
        <<<<

        Output:
        >>>>
        Link ( http://example.com/ )
        <<<<

        Expected:
        >>>>
        Link
        <<<<
    html2text_test.go:517: error: input did not match specified expression
        Input:
        >>>>
        <a href='http://example.com/'>
                <span class='a'>Link</span>
                </a>
        <<<<

        Output:
        >>>>
        Link ( http://example.com/ )
        <<<<

        Expected:
        >>>>
        Link
        <<<<
    html2text_test.go:517: error: input did not match specified expression
        Input:
        >>>>
        <a href="http://example.com/"><img src="http://example.ru/hello.jpg" alt="Example"></a>
        <<<<

        Output:
        >>>>
        Example ( http://example.com/ )
        <<<<

        Expected:
        >>>>
        Example
        <<<<
FAIL
FAIL    github.com/jaytaylor/html2text  0.003s
FAIL
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "go" arguments: ("test" "github.com/jaytaylor/html2text") exit-status: 1 term-signal: #f stop-signal: #f>
phase `check' failed after 1.0 seconds
command "go" "test" "github.com/jaytaylor/html2text" failed with status 1

**Comment by flimzy** [comment]
should be fixed by #59

**Comment by Hellseher** [comment]
All tests are passing with version `0.0.0-20230321000545-74c2419ad056`
